(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          MOTOR1-VAL
          MOTOR1
          MOTOR2-VAL
          MOTOR2
          MOTOR3-VAL
          MOTOR3
          MOTOR4-VAL
          MOTOR4
          SAT_MOTOR1-VAL
          SAT_MOTOR1
          SAT_MOTOR2-VAL
          SAT_MOTOR2
          SAT_MOTOR3-VAL
          SAT_MOTOR3
          SAT_MOTOR4-VAL
          SAT_MOTOR4
          GAZ_FEED_FORWARD-VAL
          GAZ_FEED_FORWARD
          GAZ_ALTITUDE-VAL
          GAZ_ALTITUDE
          ALTITUDE_INTEGRAL-VAL
          ALTITUDE_INTEGRAL
          VZ_REF-VAL
          VZ_REF
          U_PITCH-VAL
          U_PITCH
          U_ROLL-VAL
          U_ROLL
          U_YAW-VAL
          U_YAW
          YAW_U_I-VAL
          YAW_U_I
          U_PITCH_PLANIF-VAL
          U_PITCH_PLANIF
          U_ROLL_PLANIF-VAL
          U_ROLL_PLANIF
          U_YAW_PLANIF-VAL
          U_YAW_PLANIF
          U_GAZ_PLANIF-VAL
          U_GAZ_PLANIF
          CURRENT_MOTOR1-VAL
          CURRENT_MOTOR1
          CURRENT_MOTOR2-VAL
          CURRENT_MOTOR2
          CURRENT_MOTOR3-VAL
          CURRENT_MOTOR3
          CURRENT_MOTOR4-VAL
          CURRENT_MOTOR4
          ALTITUDE_DER-VAL
          ALTITUDE_DER
))