(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          OFFSET_PRESSURE-VAL
          OFFSET_PRESSURE
          EST_Z-VAL
          EST_Z
          EST_ZDOT-VAL
          EST_ZDOT
          EST_BIAS_PWM-VAL
          EST_BIAS_PWM
          EST_BIAIS_PRESSION-VAL
          EST_BIAIS_PRESSION
          OFFSET_US-VAL
          OFFSET_US
          PREDICTION_US-VAL
          PREDICTION_US
          COV_ALT-VAL
          COV_ALT
          COV_PWM-VAL
          COV_PWM
          COV_VITESSE-VAL
          COV_VITESSE
          BOOL_EFFET_SOL-VAL
          BOOL_EFFET_SOL
          SOMME_INNO-VAL
          SOMME_INNO
          FLAG_REJET_US-VAL
          FLAG_REJET_US
          U_MULTISINUS-VAL
          U_MULTISINUS
          GAZ_ALTITUDE-VAL
          GAZ_ALTITUDE
          FLAG_MULTISINUS-VAL
          FLAG_MULTISINUS
          FLAG_MULTISINUS_DEBUT-VAL
          FLAG_MULTISINUS_DEBUT
))