(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          CTRL_STATE-VAL
          CTRL_STATE
          VBAT_FLYING_PERCENTAGE-VAL
          VBAT_FLYING_PERCENTAGE
          THETA-VAL
          THETA
          PHI-VAL
          PHI
          PSI-VAL
          PSI
          ALTITUDE-VAL
          ALTITUDE
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          NUM_FRAMES-VAL
          NUM_FRAMES
          DETECTION_CAMERA_TYPE-VAL
          DETECTION_CAMERA_TYPE
))