(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          ALTITUDE_VISION-VAL
          ALTITUDE_VISION
          ALTITUDE_VZ-VAL
          ALTITUDE_VZ
          ALTITUDE_REF-VAL
          ALTITUDE_REF
          ALTITUDE_RAW-VAL
          ALTITUDE_RAW
          OBS_ACCZ-VAL
          OBS_ACCZ
          OBS_ALT-VAL
          OBS_ALT
          OBS_X-VAL
          OBS_X
          OBS_STATE-VAL
          OBS_STATE
          EST_VB-VAL
          EST_VB
          EST_STATE-VAL
          EST_STATE
))