(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          RAW_GYROS-VAL
          RAW_GYROS
          RAW_GYROS_110-VAL
          RAW_GYROS_110
          VBAT_RAW-VAL
          VBAT_RAW
          US_DEBUT_ECHO-VAL
          US_DEBUT_ECHO
          US_FIN_ECHO-VAL
          US_FIN_ECHO
          US_ASSOCIATION_ECHO-VAL
          US_ASSOCIATION_ECHO
          US_DISTANCE_ECHO-VAL
          US_DISTANCE_ECHO
          US_COURBE_TEMPS-VAL
          US_COURBE_TEMPS
          US_COURBE_VALEUR-VAL
          US_COURBE_VALEUR
          US_COURBE_REF-VAL
          US_COURBE_REF
          FLAG_ECHO_INI-VAL
          FLAG_ECHO_INI
          NB_ECHO-VAL
          NB_ECHO
          SUM_ECHO-VAL
          SUM_ECHO
          ALT_TEMP_RAW-VAL
          ALT_TEMP_RAW
          GRADIENT-VAL
          GRADIENT
))