(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          WIND_SPEED-VAL
          WIND_SPEED
          WIND_ANGLE-VAL
          WIND_ANGLE
          WIND_COMPENSATION_THETA-VAL
          WIND_COMPENSATION_THETA
          WIND_COMPENSATION_PHI-VAL
          WIND_COMPENSATION_PHI
          STATE_X1-VAL
          STATE_X1
          STATE_X2-VAL
          STATE_X2
          STATE_X3-VAL
          STATE_X3
          STATE_X4-VAL
          STATE_X4
          STATE_X5-VAL
          STATE_X5
          STATE_X6-VAL
          STATE_X6
          MAGNETO_DEBUG1-VAL
          MAGNETO_DEBUG1
          MAGNETO_DEBUG2-VAL
          MAGNETO_DEBUG2
          MAGNETO_DEBUG3-VAL
          MAGNETO_DEBUG3
))