(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          QUANT-VAL
          QUANT
          FRAME_SIZE-VAL
          FRAME_SIZE
          FRAME_NUMBER-VAL
          FRAME_NUMBER
          ATCMD_REF_SEQ-VAL
          ATCMD_REF_SEQ
          ATCMD_MEAN_REF_GAP-VAL
          ATCMD_MEAN_REF_GAP
          ATCMD_VAR_REF_GAP-VAL
          ATCMD_VAR_REF_GAP
          ATCMD_REF_QUALITY-VAL
          ATCMD_REF_QUALITY
          DESIRED_BITRATE-VAL
          DESIRED_BITRATE
          DATA2-VAL
          DATA2
          DATA3-VAL
          DATA3
          DATA4-VAL
          DATA4
          DATA5-VAL
          DATA5
          FIFO_QUEUE_LEVEL-VAL
          FIFO_QUEUE_LEVEL
))