(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          REF_THETA-VAL
          REF_THETA
          REF_PHI-VAL
          REF_PHI
          REF_THETA_I-VAL
          REF_THETA_I
          REF_PHI_I-VAL
          REF_PHI_I
          REF_PITCH-VAL
          REF_PITCH
          REF_ROLL-VAL
          REF_ROLL
          REF_YAW-VAL
          REF_YAW
          REF_PSI-VAL
          REF_PSI
          VX_REF-VAL
          VX_REF
          VY_REF-VAL
          VY_REF
          THETA_MOD-VAL
          THETA_MOD
          PHI_MOD-VAL
          PHI_MOD
          K_V_X-VAL
          K_V_X
          K_V_Y-VAL
          K_V_Y
          K_MODE-VAL
          K_MODE
          UI_TIME-VAL
          UI_TIME
          UI_THETA-VAL
          UI_THETA
          UI_PHI-VAL
          UI_PHI
          UI_PSI-VAL
          UI_PSI
          UI_PSI_ACCURACY-VAL
          UI_PSI_ACCURACY
          UI_SEQ-VAL
          UI_SEQ
))