(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          MX-VAL
          MX
          MY-VAL
          MY
          MZ-VAL
          MZ
          MAGNETO_RAW-VAL
          MAGNETO_RAW
          MAGNETO_RECTIFIED-VAL
          MAGNETO_RECTIFIED
          MAGNETO_OFFSET-VAL
          MAGNETO_OFFSET
          HEADING_UNWRAPPED-VAL
          HEADING_UNWRAPPED
          HEADING_GYRO_UNWRAPPED-VAL
          HEADING_GYRO_UNWRAPPED
          HEADING_FUSION_UNWRAPPED-VAL
          HEADING_FUSION_UNWRAPPED
          MAGNETO_CALIBRATION_OK-VAL
          MAGNETO_CALIBRATION_OK
          MAGNETO_STATE-VAL
          MAGNETO_STATE
          MAGNETO_RADIUS-VAL
          MAGNETO_RADIUS
          ERROR_MEAN-VAL
          ERROR_MEAN
          ERROR_VAR-VAL
          ERROR_VAR
))