(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          VISION_STATE-VAL
          VISION_STATE
          VISION_MISC-VAL
          VISION_MISC
          VISION_PHI_TRIM-VAL
          VISION_PHI_TRIM
          VISION_PHI_REF_PROP-VAL
          VISION_PHI_REF_PROP
          VISION_THETA_TRIM-VAL
          VISION_THETA_TRIM
          VISION_THETA_REF_PROP-VAL
          VISION_THETA_REF_PROP
          NEW_RAW_PICTURE-VAL
          NEW_RAW_PICTURE
          THETA_CAPTURE-VAL
          THETA_CAPTURE
          PHI_CAPTURE-VAL
          PHI_CAPTURE
          PSI_CAPTURE-VAL
          PSI_CAPTURE
          ALTITUDE_CAPTURE-VAL
          ALTITUDE_CAPTURE
          TIME_CAPTURE-VAL
          TIME_CAPTURE
          BODY_V-VAL
          BODY_V
          DELTA_PHI-VAL
          DELTA_PHI
          DELTA_THETA-VAL
          DELTA_THETA
          DELTA_PSI-VAL
          DELTA_PSI
          GOLD_DEFINED-VAL
          GOLD_DEFINED
          GOLD_RESET-VAL
          GOLD_RESET
          GOLD_X-VAL
          GOLD_X
          GOLD_Y-VAL
          GOLD_Y
))