(cl:in-package ardrone_autonomy-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_TIME-VAL
          DRONE_TIME
          TAG-VAL
          TAG
          SIZE-VAL
          SIZE
          NB_DETECTED-VAL
          NB_DETECTED
          TYPE-VAL
          TYPE
          XC-VAL
          XC
          YC-VAL
          YC
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          DIST-VAL
          DIST
          ORIENTATION_ANGLE-VAL
          ORIENTATION_ANGLE
          ROTATION-VAL
          ROTATION
          TRANSLATION-VAL
          TRANSLATION
          CAMERA_SOURCE-VAL
          CAMERA_SOURCE
))