// Generated by gencpp from file ardrone_autonomy/CamSelect.msg
// DO NOT EDIT!


#ifndef ARDRONE_AUTONOMY_MESSAGE_CAMSELECT_H
#define ARDRONE_AUTONOMY_MESSAGE_CAMSELECT_H

#include <ros/service_traits.h>


#include <ardrone_autonomy/CamSelectRequest.h>
#include <ardrone_autonomy/CamSelectResponse.h>


namespace ardrone_autonomy
{

struct CamSelect
{

typedef CamSelectRequest Request;
typedef CamSelectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CamSelect
} // namespace ardrone_autonomy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ardrone_autonomy::CamSelect > {
  static const char* value()
  {
    return "bbeb5212f8ee1d6da7ff0d1169124280";
  }

  static const char* value(const ::ardrone_autonomy::CamSelect&) { return value(); }
};

template<>
struct DataType< ::ardrone_autonomy::CamSelect > {
  static const char* value()
  {
    return "ardrone_autonomy/CamSelect";
  }

  static const char* value(const ::ardrone_autonomy::CamSelect&) { return value(); }
};


// service_traits::MD5Sum< ::ardrone_autonomy::CamSelectRequest> should match 
// service_traits::MD5Sum< ::ardrone_autonomy::CamSelect > 
template<>
struct MD5Sum< ::ardrone_autonomy::CamSelectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ardrone_autonomy::CamSelect >::value();
  }
  static const char* value(const ::ardrone_autonomy::CamSelectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardrone_autonomy::CamSelectRequest> should match 
// service_traits::DataType< ::ardrone_autonomy::CamSelect > 
template<>
struct DataType< ::ardrone_autonomy::CamSelectRequest>
{
  static const char* value()
  {
    return DataType< ::ardrone_autonomy::CamSelect >::value();
  }
  static const char* value(const ::ardrone_autonomy::CamSelectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ardrone_autonomy::CamSelectResponse> should match 
// service_traits::MD5Sum< ::ardrone_autonomy::CamSelect > 
template<>
struct MD5Sum< ::ardrone_autonomy::CamSelectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ardrone_autonomy::CamSelect >::value();
  }
  static const char* value(const ::ardrone_autonomy::CamSelectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardrone_autonomy::CamSelectResponse> should match 
// service_traits::DataType< ::ardrone_autonomy::CamSelect > 
template<>
struct DataType< ::ardrone_autonomy::CamSelectResponse>
{
  static const char* value()
  {
    return DataType< ::ardrone_autonomy::CamSelect >::value();
  }
  static const char* value(const ::ardrone_autonomy::CamSelectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDRONE_AUTONOMY_MESSAGE_CAMSELECT_H
