// Generated by gencpp from file ardrone_autonomy/FlightAnim.msg
// DO NOT EDIT!


#ifndef ARDRONE_AUTONOMY_MESSAGE_FLIGHTANIM_H
#define ARDRONE_AUTONOMY_MESSAGE_FLIGHTANIM_H

#include <ros/service_traits.h>


#include <ardrone_autonomy/FlightAnimRequest.h>
#include <ardrone_autonomy/FlightAnimResponse.h>


namespace ardrone_autonomy
{

struct FlightAnim
{

typedef FlightAnimRequest Request;
typedef FlightAnimResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FlightAnim
} // namespace ardrone_autonomy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ardrone_autonomy::FlightAnim > {
  static const char* value()
  {
    return "b67c0059d7339761bcde13f61a58763f";
  }

  static const char* value(const ::ardrone_autonomy::FlightAnim&) { return value(); }
};

template<>
struct DataType< ::ardrone_autonomy::FlightAnim > {
  static const char* value()
  {
    return "ardrone_autonomy/FlightAnim";
  }

  static const char* value(const ::ardrone_autonomy::FlightAnim&) { return value(); }
};


// service_traits::MD5Sum< ::ardrone_autonomy::FlightAnimRequest> should match 
// service_traits::MD5Sum< ::ardrone_autonomy::FlightAnim > 
template<>
struct MD5Sum< ::ardrone_autonomy::FlightAnimRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ardrone_autonomy::FlightAnim >::value();
  }
  static const char* value(const ::ardrone_autonomy::FlightAnimRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardrone_autonomy::FlightAnimRequest> should match 
// service_traits::DataType< ::ardrone_autonomy::FlightAnim > 
template<>
struct DataType< ::ardrone_autonomy::FlightAnimRequest>
{
  static const char* value()
  {
    return DataType< ::ardrone_autonomy::FlightAnim >::value();
  }
  static const char* value(const ::ardrone_autonomy::FlightAnimRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ardrone_autonomy::FlightAnimResponse> should match 
// service_traits::MD5Sum< ::ardrone_autonomy::FlightAnim > 
template<>
struct MD5Sum< ::ardrone_autonomy::FlightAnimResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ardrone_autonomy::FlightAnim >::value();
  }
  static const char* value(const ::ardrone_autonomy::FlightAnimResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ardrone_autonomy::FlightAnimResponse> should match 
// service_traits::DataType< ::ardrone_autonomy::FlightAnim > 
template<>
struct DataType< ::ardrone_autonomy::FlightAnimResponse>
{
  static const char* value()
  {
    return DataType< ::ardrone_autonomy::FlightAnim >::value();
  }
  static const char* value(const ::ardrone_autonomy::FlightAnimResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDRONE_AUTONOMY_MESSAGE_FLIGHTANIM_H
