// Generated by gencpp from file tum_ardrone/SetInitialReachDistance.msg
// DO NOT EDIT!


#ifndef TUM_ARDRONE_MESSAGE_SETINITIALREACHDISTANCE_H
#define TUM_ARDRONE_MESSAGE_SETINITIALREACHDISTANCE_H

#include <ros/service_traits.h>


#include <tum_ardrone/SetInitialReachDistanceRequest.h>
#include <tum_ardrone/SetInitialReachDistanceResponse.h>


namespace tum_ardrone
{

struct SetInitialReachDistance
{

typedef SetInitialReachDistanceRequest Request;
typedef SetInitialReachDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitialReachDistance
} // namespace tum_ardrone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_ardrone::SetInitialReachDistance > {
  static const char* value()
  {
    return "e42c385d60567bcc18375e4218bebdff";
  }

  static const char* value(const ::tum_ardrone::SetInitialReachDistance&) { return value(); }
};

template<>
struct DataType< ::tum_ardrone::SetInitialReachDistance > {
  static const char* value()
  {
    return "tum_ardrone/SetInitialReachDistance";
  }

  static const char* value(const ::tum_ardrone::SetInitialReachDistance&) { return value(); }
};


// service_traits::MD5Sum< ::tum_ardrone::SetInitialReachDistanceRequest> should match 
// service_traits::MD5Sum< ::tum_ardrone::SetInitialReachDistance > 
template<>
struct MD5Sum< ::tum_ardrone::SetInitialReachDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_ardrone::SetInitialReachDistance >::value();
  }
  static const char* value(const ::tum_ardrone::SetInitialReachDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_ardrone::SetInitialReachDistanceRequest> should match 
// service_traits::DataType< ::tum_ardrone::SetInitialReachDistance > 
template<>
struct DataType< ::tum_ardrone::SetInitialReachDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::tum_ardrone::SetInitialReachDistance >::value();
  }
  static const char* value(const ::tum_ardrone::SetInitialReachDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_ardrone::SetInitialReachDistanceResponse> should match 
// service_traits::MD5Sum< ::tum_ardrone::SetInitialReachDistance > 
template<>
struct MD5Sum< ::tum_ardrone::SetInitialReachDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_ardrone::SetInitialReachDistance >::value();
  }
  static const char* value(const ::tum_ardrone::SetInitialReachDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_ardrone::SetInitialReachDistanceResponse> should match 
// service_traits::DataType< ::tum_ardrone::SetInitialReachDistance > 
template<>
struct DataType< ::tum_ardrone::SetInitialReachDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::tum_ardrone::SetInitialReachDistance >::value();
  }
  static const char* value(const ::tum_ardrone::SetInitialReachDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ARDRONE_MESSAGE_SETINITIALREACHDISTANCE_H
