// Generated by gencpp from file tum_ardrone/SetStayTime.msg
// DO NOT EDIT!


#ifndef TUM_ARDRONE_MESSAGE_SETSTAYTIME_H
#define TUM_ARDRONE_MESSAGE_SETSTAYTIME_H

#include <ros/service_traits.h>


#include <tum_ardrone/SetStayTimeRequest.h>
#include <tum_ardrone/SetStayTimeResponse.h>


namespace tum_ardrone
{

struct SetStayTime
{

typedef SetStayTimeRequest Request;
typedef SetStayTimeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetStayTime
} // namespace tum_ardrone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_ardrone::SetStayTime > {
  static const char* value()
  {
    return "d3a1853188ab17a3b9ca3ccc971be236";
  }

  static const char* value(const ::tum_ardrone::SetStayTime&) { return value(); }
};

template<>
struct DataType< ::tum_ardrone::SetStayTime > {
  static const char* value()
  {
    return "tum_ardrone/SetStayTime";
  }

  static const char* value(const ::tum_ardrone::SetStayTime&) { return value(); }
};


// service_traits::MD5Sum< ::tum_ardrone::SetStayTimeRequest> should match 
// service_traits::MD5Sum< ::tum_ardrone::SetStayTime > 
template<>
struct MD5Sum< ::tum_ardrone::SetStayTimeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_ardrone::SetStayTime >::value();
  }
  static const char* value(const ::tum_ardrone::SetStayTimeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_ardrone::SetStayTimeRequest> should match 
// service_traits::DataType< ::tum_ardrone::SetStayTime > 
template<>
struct DataType< ::tum_ardrone::SetStayTimeRequest>
{
  static const char* value()
  {
    return DataType< ::tum_ardrone::SetStayTime >::value();
  }
  static const char* value(const ::tum_ardrone::SetStayTimeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_ardrone::SetStayTimeResponse> should match 
// service_traits::MD5Sum< ::tum_ardrone::SetStayTime > 
template<>
struct MD5Sum< ::tum_ardrone::SetStayTimeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_ardrone::SetStayTime >::value();
  }
  static const char* value(const ::tum_ardrone::SetStayTimeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_ardrone::SetStayTimeResponse> should match 
// service_traits::DataType< ::tum_ardrone::SetStayTime > 
template<>
struct DataType< ::tum_ardrone::SetStayTimeResponse>
{
  static const char* value()
  {
    return DataType< ::tum_ardrone::SetStayTime >::value();
  }
  static const char* value(const ::tum_ardrone::SetStayTimeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ARDRONE_MESSAGE_SETSTAYTIME_H
