// Generated by gencpp from file tum_ardrone/SetStayWithinDistance.msg
// DO NOT EDIT!


#ifndef TUM_ARDRONE_MESSAGE_SETSTAYWITHINDISTANCE_H
#define TUM_ARDRONE_MESSAGE_SETSTAYWITHINDISTANCE_H

#include <ros/service_traits.h>


#include <tum_ardrone/SetStayWithinDistanceRequest.h>
#include <tum_ardrone/SetStayWithinDistanceResponse.h>


namespace tum_ardrone
{

struct SetStayWithinDistance
{

typedef SetStayWithinDistanceRequest Request;
typedef SetStayWithinDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetStayWithinDistance
} // namespace tum_ardrone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_ardrone::SetStayWithinDistance > {
  static const char* value()
  {
    return "e42c385d60567bcc18375e4218bebdff";
  }

  static const char* value(const ::tum_ardrone::SetStayWithinDistance&) { return value(); }
};

template<>
struct DataType< ::tum_ardrone::SetStayWithinDistance > {
  static const char* value()
  {
    return "tum_ardrone/SetStayWithinDistance";
  }

  static const char* value(const ::tum_ardrone::SetStayWithinDistance&) { return value(); }
};


// service_traits::MD5Sum< ::tum_ardrone::SetStayWithinDistanceRequest> should match 
// service_traits::MD5Sum< ::tum_ardrone::SetStayWithinDistance > 
template<>
struct MD5Sum< ::tum_ardrone::SetStayWithinDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_ardrone::SetStayWithinDistance >::value();
  }
  static const char* value(const ::tum_ardrone::SetStayWithinDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_ardrone::SetStayWithinDistanceRequest> should match 
// service_traits::DataType< ::tum_ardrone::SetStayWithinDistance > 
template<>
struct DataType< ::tum_ardrone::SetStayWithinDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::tum_ardrone::SetStayWithinDistance >::value();
  }
  static const char* value(const ::tum_ardrone::SetStayWithinDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_ardrone::SetStayWithinDistanceResponse> should match 
// service_traits::MD5Sum< ::tum_ardrone::SetStayWithinDistance > 
template<>
struct MD5Sum< ::tum_ardrone::SetStayWithinDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_ardrone::SetStayWithinDistance >::value();
  }
  static const char* value(const ::tum_ardrone::SetStayWithinDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_ardrone::SetStayWithinDistanceResponse> should match 
// service_traits::DataType< ::tum_ardrone::SetStayWithinDistance > 
template<>
struct DataType< ::tum_ardrone::SetStayWithinDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::tum_ardrone::SetStayWithinDistance >::value();
  }
  static const char* value(const ::tum_ardrone::SetStayWithinDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ARDRONE_MESSAGE_SETSTAYWITHINDISTANCE_H
